site_name: The Kai Project
site_url: https://Myyura.github.io/the_kai_project/
repo_url: https://github.com/Myyura/the_kai_project
edit_uri: https://github.com/Myyura/the_kai_project
repo_name: myyura/the_kai_project
remote_name: https://github.com/Myyura/the_kai_project
docs_dir: "docs/" # where to find the markdown files
site_dir: "site/" # where to publish to

theme:
  name: material
  palette:
    primary: blue grey
  custom_dir: docs/overrides/

  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

plugins:
  - search
  - img2fig
  - tags:
      tags_file: tags.md
      tags_hierarchy: true

extra_javascript:
  - overrides/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"

copyright: <a href="https://github.com/Myyura/the_kai_project" target="_blank">© 2024 The Kai Project</a> All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Myyura/the_kai_project
      name: Github
    - icon: fontawesome/regular/envelope
      link: mailto:<376672994@qq.com> #联系方式
      name: Email

# nav
nav:
  - 過去問:
    - 项目介绍: index.md
    - 東京大学:
      - 理学系研究科:
        - 物理学専攻:
          - 2022年度:
            - 専門科目 第1問: kakomonn/tokyo_university/science/phys_2022_sennmon_1.md
          - 2020年度:
            - 物理学 第1問: kakomonn/tokyo_university/science/phys_2020_phys_1.md
            - 物理学 第2問: kakomonn/tokyo_university/science/phys_2020_phys_2.md
        - 天文学専攻:
          - 2023年度:
            - 天文学: kakomonn/tokyo_university/science/astron_2023_astron.md
        - 化学専攻:
          - 2020年度:
            - 数理科学: kakomonn/tokyo_university/science/chem_2020_math_1.md
      - 工学系研究科:
        - 共通:
          - 2023年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2023_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/engineering/kyotsu_2023_math_2.md
          - 2022年度:
            - 数学1: kakomonn/tokyo_university/engineering/kyotsu_2022_math_1.md
            - 数学2: kakomonn/tokyo_university/engineering/kyotsu_2022_math_2.md
            - 数学3: kakomonn/tokyo_university/engineering/kyotsu_2022_math_3.md
            - 物理学1: kakomonn/tokyo_university/engineering/kyotsu_2022_phys_1.md
          - 2021年度:
            - 数学1: kakomonn/tokyo_university/engineering/kyotsu_2021_math_1.md
            - 数学2: kakomonn/tokyo_university/engineering/kyotsu_2021_math_2.md
            - 数学3: kakomonn/tokyo_university/engineering/kyotsu_2021_math_3.md
            - 物理学1: kakomonn/tokyo_university/engineering/kyotsu_2021_phys_1.md
          - 2020年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2020_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/engineering/kyotsu_2020_math_2.md
          - 2017年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_2.md
            - 数学 第3問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_3.md
            - 数学 第4問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_4.md
            - 数学 第5問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_5.md
        - 物理工学専攻:
          - 2020年度:
            - 物理学 第3問: kakomonn/tokyo_university/engineering/ap_2020_phys_3.md
        - 技術経営戦略学専攻:
          - 2022年度:
            - セッション 1: kakomonn/tokyo_university/engineering/tmi_2022_session_1.md
      - 情報理工学研究科:
        - 共通:
          - 2023年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2023_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/IST/kyotsu_2023_math_2.md
          - 2022年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2022_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/IST/kyotsu_2022_math_2.md
            - 数学 第3問: kakomonn/tokyo_university/IST/kyotsu_2022_math_3.md
          - 2020年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2020_math_1.md
          - 2018年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2018_math_1.md
          - 2017年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2017_math_1.md
      - 新領域創成科学研究科:
        - 物質系専攻:
          - 2020年度:
            - 第3問: kakomonn/tokyo_university/frontier_sciences/materials_2020_3.md
        - 複雑理工学専攻:
          - 2020年度:
            - 第1問: kakomonn/tokyo_university/frontier_sciences/cse_2020_1.md
            - 第2問: kakomonn/tokyo_university/frontier_sciences/cse_2020_2.md
            - 第3問: kakomonn/tokyo_university/frontier_sciences/cse_2020_3.md
            - 第4問: kakomonn/tokyo_university/frontier_sciences/cse_2020_4.md
          - 2019年度:
            - 第4問: kakomonn/tokyo_university/frontier_sciences/cse_2019_4.md
            - 第8問: kakomonn/tokyo_university/frontier_sciences/cse_2019_8.md
        - 海洋技術環境学専攻:
          - 2022年度:
            - 第1~6問: kakomonn/tokyo_university/frontier_sciences/otpe_2022_all.md
          - 2020年度:
            - 第1~9問: kakomonn/tokyo_university/frontier_sciences/otpe_2020_all.md
          - 2019年度:
            - 第1~9問: kakomonn/tokyo_university/frontier_sciences/otpe_2019_all.md
      - 総合文化研究科:
        - 広域科学専攻・広域システム科学系: 
          - 2020年度:
            - 総合科目 第3問: kakomonn/tokyo_university/art_and_sciences/system_2020_3.md
      - 情報学環・学際情報学府:
        - 学際情報学専攻・生物統計情報学コース:
          - 2020年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2020_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2020_2.md
          - 2019年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2019_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2019_2.md
          - 2018年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2018_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2018_2.md
      - 数理科学研究科:
        - 数理科学専攻:
          - 2022年度:
            - 専門科目 A 第1問: kakomonn/tokyo_university/mathematical_sciences/ms_2022_A_1.md
          - 2021年度:
            - 専門科目 B 第16問: kakomonn/tokyo_university/mathematical_sciences/ms_2021_B_16.md
          - 2020年度:
            - 専門科目 A 第1問: kakomonn/tokyo_university/mathematical_sciences/ms_2020_A_1.md
    - 京都大学:
      - 理学研究科:
        - 数学・数理解析専攻:
          - 2024年度:
            - 基礎科目 [1] ~ [4]: kakomonn/kyoto_university/science/math_2024_kiso_1_4.md
            - 専門科目 [13]: kakomonn/kyoto_university/science/math_2024_senmon_13.md
          - 2023年度:
            - 基礎科目 [1] ~ [3]: kakomonn/kyoto_university/science/math_2023_kiso_1_3.md
        - 物理学・宇宙物理学専攻:
          - 2022年度:
            - I-3 (AB): kakomonn/kyoto_university/science/phys_2022_I_3_AB.md
            - II-2C: kakomonn/kyoto_university/science/phys_2022_II_2_C.md
          - 2020年度:
            - I-2 (AB): kakomonn/kyoto_university/science/phys_2020_I_2_AB.md
        - 地球惑星科学専攻:
          - 2023年度:
            - 基礎科目 問題1: kakomonn/kyoto_university/science/eps_2023_kiso_1.md
        - 化学専攻:
          - 2023年度:
            - 物理学 基礎: kakomonn/kyoto_university/science/chem_2023_phys_kiso.md
      - 情報学研究科:
        - 数理工学専攻:
          - 2023年実施:
            - 専門科目 グラフ理論: kakomonn/kyoto_university/informatics/amp_2023_graph_theory.md
          - 2022年実施:
            - 専門科目 グラフ理論: kakomonn/kyoto_university/informatics/amp_2022_graph_theory.md
          - 2021年実施:
            - 基礎科目 アルゴリズム基礎: kakomonn/kyoto_university/informatics/amp_2021_algorithm.md
            - 専門科目 グラフ理論: kakomonn/kyoto_university/informatics/amp_2021_graph_theory.md
          - 2020年実施:
            - 専門科目 グラフ理論: kakomonn/kyoto_university/informatics/amp_2020_graph_theory.md
          - 2019年実施:
            - 基礎科目 アルゴリズム基礎: kakomonn/kyoto_university/informatics/amp_2019_algorithm.md
            - 専門科目 グラフ理論: kakomonn/kyoto_university/informatics/amp_2019_graph_theory.md
        - 知能情報学専攻:
          - 2021年実施:
            - 情報学基礎 F1-2: kakomonn/kyoto_university/informatics/ist_2021_kiso_f1_2.md
          - 2019年実施:
            - 情報学基礎 F1-1: kakomonn/kyoto_university/informatics/ist_2019_kiso_f1_1.md
            - 専門科目 S-2 統計学: kakomonn/kyoto_university/informatics/ist_2019_senmon_s_2.md
        - 先端数理科学専攻:
          - 2021年実施:
            - 基礎科目1 基礎科目2: kakomonn/kyoto_university/informatics/ams_2021_kiso_1_2.md
        - システム科学専攻:
          - 2019年実施:
            - 専門科目 確率統計: kakomonn/kyoto_university/informatics/sys_2019_senmon_stat.md
        - 通信情報システム専攻:
          - 2021年実施:
            - 専門基礎A [A-1]: kakomonn/kyoto_university/informatics/cce_2021_senmonkiso_A_1.md
            - 専門基礎A [A-2]: kakomonn/kyoto_university/informatics/cce_2021_senmonkiso_A_2.md
      - 経営管理大学院:
        - 2023年度:
          - 数学 第1問: kakomonn/kyoto_university/management/2023_math_1.md
    - 東北大学:
      - 理学研究科:
        - 数学専攻:
          - 2023年度:
            - 共通問題 [1]: kakomonn/tohoku_university/science/math_2023_kyotsu_1.md
        - 物理学専攻:
          - 2019年度:
            - 問題1（基礎数学）: kakomonn/tohoku_university/science/phys_2019_1.md
            - 問題2（力学）: kakomonn/tohoku_university/science/phys_2019_2.md
            - 問題3（電磁気学）: kakomonn/tohoku_university/science/phys_2019_3.md
            - 問題4（量子力学）: kakomonn/tohoku_university/science/phys_2019_4.md
            - 問題5（熱・統計力学）: kakomonn/tohoku_university/science/phys_2019_5.md
        - 地球物理学専攻:
          - 2023年度 [7]: kakomonn/tohoku_university/science/gp_2023_7.md
        - 化学専攻:
          - 2023年度 2B: kakomonn/tohoku_university/science/chem_2023_2B.md
      - 工学研究科:
        - 機械系:
          - 2022年実施:
            - 数学A 1: kakomonn/tohoku_university/engineering/mech_2022_math_A1.md
            - 数学A 2: kakomonn/tohoku_university/engineering/mech_2022_math_A2.md
            - 数学A 3: kakomonn/tohoku_university/engineering/mech_2022_math_A3.md
        - 量子エネルギー工学専攻:
          - 2023年実施:
            - 8月 数学A 1: kakomonn/tohoku_university/engineering/qse_2023_math_A_1.md
        - 電気・情報系:
          - 2023年実施:
            - 8月 基礎科目 問題1: kakomonn/tohoku_university/engineering/ecei_2023_8_kiso_1.md
            - 8月 基礎科目 問題4: kakomonn/tohoku_university/engineering/ecei_2023_8_kiso_4.md
          - 2022年実施:
            - 3月 基礎科目 問題6: kakomonn/tohoku_university/engineering/ecei_2022_3_kiso_6.md
          - 2021年実施:
            - 8月 基礎科目 問題6: kakomonn/tohoku_university/engineering/ecei_2021_8_kiso_6.md
          - 2019年実施:
            - 3月 基礎科目 問題4: kakomonn/tohoku_university/engineering/ecei_2019_3_kiso_4.md
          - 2018年実施:
            - 3月 基礎科目 問題4: kakomonn/tohoku_university/engineering/ecei_2018_3_kiso_4.md
          - 2015年実施:
            - 8月 基礎科目 問題4: kakomonn/tohoku_university/engineering/ecei_2015_8_kiso_4.md
        - 応用物理学専攻:
          - 2019年実施:
            - 問題1 量子力学: kakomonn/tohoku_university/engineering/apph_2019_1.md
            - 問題2 力学: kakomonn/tohoku_university/engineering/apph_2019_2.md
        - 化学・バイオ系:
          - 2023年度:
            - 基礎科目 無機・物理化学: kakomonn/tohoku_university/engineering/che_2023_inorg_phys_chem.md
        - マテリアル・開発系:
          - 2022年実施:
            - 【数学-1,2】: kakomonn/tohoku_university/engineering/material_2022_math_1_2.md
        - 土木工学専攻:
          - 2023年実施:
            - 基礎科目 [1] 微分積分: kakomonn/tohoku_university/engineering/civil_2023_2_kiso_1.md
            - 基礎科目 [3] 確率統計: kakomonn/tohoku_university/engineering/civil_2023_2_kiso_3.md
      - 情報科学研究科:
        - 数学教室:
          - 2021年実施:
            - 8月 [7]: kakomonn/tohoku_university/information_sciences/math_2021_8_7.md
          - 2019年実施:
            - 8月 [6]: kakomonn/tohoku_university/information_sciences/math_2019_8_6.md
          - 2017年実施:
            - 8月 [6]: kakomonn/tohoku_university/information_sciences/math_2017_8_6.md
          - 2016年実施:
            - 8月 [6]: kakomonn/tohoku_university/information_sciences/math_2016_8_6.md
        - 社会科学群:
          - 2022年実施:
            - 8月 問題E-3: kakomonn/tohoku_university/information_sciences/social_2022_8_E3.md
      - 環境科学研究科:
        - エネルギー環境群:
          - 2022年実施:
            - 8月 基礎科目 数学1: kakomonn/tohoku_university/environmental_studies/ee_2022_8_math_1.md
            - 8月 基礎科目 数学2: kakomonn/tohoku_university/environmental_studies/ee_2022_8_math_2.md
      - 医工学研究科:
        - 医学系コース:
          - 2023年実施:
            - 数学基礎 問題1-3: kakomonn/tohoku_university/biomedical_engineering/med_2023_math_1_3.md
            - 数学基礎 問題4-6: kakomonn/tohoku_university/biomedical_engineering/med_2023_math_4_6.md
          - 2022年実施:
            - 数学基礎 問題1-3: kakomonn/tohoku_university/biomedical_engineering/med_2022_math_1_3.md
            - 数学基礎 問題4-6: kakomonn/tohoku_university/biomedical_engineering/med_2022_math_4_6.md
    - 大阪大学:
      - 理学研究科:
        - 物理学専攻:
          - 2020年度:
            - 問題1: kakomonn/osaka_university/science/phys_2020_1.md
      # - 工学研究科:
      # - 基礎工学研究科:
      # - 情報科学研究科:
        - 情報基礎数学専攻:
          - 2021年度:
            - 数学1-3: kakomonn/osaka_university/IST/math_2021_1_3.md
            - 数学4-5: kakomonn/osaka_university/IST/math_2021_4_5.md
        - 情報数理学:
          - 2020年度:
            - 数理基礎: kakomonn/osaka_university/IST/IPS_2020_suurikiso.md
            - 数学解析: kakomonn/osaka_university/IST/IPS_2020_suugakukaiseki.md
        - 情報工学:
          - 2020年度:
            - アルゴリズムとプログラミング: kakomonn/osaka_university/IST/ie_2020_algorithm_programming.md