site_name: The Kai Project
site_url: https://Myyura.github.io/the_kai_project/
repo_url: https://github.com/Myyura/the_kai_project
edit_uri: https://github.com/Myyura/the_kai_project
repo_name: myyura/the_kai_project
remote_name: https://github.com/Myyura/the_kai_project
docs_dir: "docs/" # where to find the markdown files
site_dir: "site/" # where to publish to

theme:
  name: material
  palette:
    primary: blue grey
  custom_dir: docs/overrides/

  features:
      - content.action.edit
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.prune
      - navigation.footer
      - navigation.tracking
      - navigation.instant
      - navigation.instant.progress
      - navigation.indexes
      - navigation.sections # navigation.expand or navigation.sections
      - content.tabs.link # all code tabs change simultaneously

plugins:
    - search
    - img2fig

extra_javascript:
  - overrides/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"

copyright: <a href="https://github.com/Myyura/the_kai_project" target="_blank">© 2024 The Kai Project</a> All rights reserved.

# nav
nav:
  - 過去問:
    - 项目介绍: index.md
    - 東京大学:
      - 理学系研究科:
        - 物理学専攻:
          - 2022年度:
            - 専門科目 第1問: kakomonn/tokyo_university/science/phys_2022_sennmon_1.md
          - 2020年度:
            - 物理学 第1問: kakomonn/tokyo_university/science/phys_2020_phys_1.md
            - 物理学 第2問: kakomonn/tokyo_university/science/phys_2020_phys_2.md
        - 天文学専攻:
          - 2023年度:
            - 天文学: kakomonn/tokyo_university/science/astron_2023_astron.md
        - 化学専攻:
          - 2020年度:
            - 数理科学: kakomonn/tokyo_university/science/chem_2020_math_1.md
      - 工学系研究科:
        - 共通:
          - 2023年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2023_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/engineering/kyotsu_2023_math_2.md
          - 2022年度:
            - 数学1: kakomonn/tokyo_university/engineering/kyotsu_2022_math_1.md
            - 数学2: kakomonn/tokyo_university/engineering/kyotsu_2022_math_2.md
            - 数学3: kakomonn/tokyo_university/engineering/kyotsu_2022_math_3.md
            - 物理学1: kakomonn/tokyo_university/engineering/kyotsu_2022_phys_1.md
          - 2021年度:
            - 数学1: kakomonn/tokyo_university/engineering/kyotsu_2021_math_1.md
            - 数学2: kakomonn/tokyo_university/engineering/kyotsu_2021_math_2.md
            - 数学3: kakomonn/tokyo_university/engineering/kyotsu_2021_math_3.md
            - 物理学1: kakomonn/tokyo_university/engineering/kyotsu_2021_phys_1.md
          - 2020年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2020_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/engineering/kyotsu_2020_math_2.md
          - 2017年度:
            - 数学 第1問: kakomonn/tokyo_university/engineering/kyotsu_2017_math_1.md
        - 物理工学専攻:
          - 2020年度:
            - 物理学 第3問: kakomonn/tokyo_university/engineering/ap_2020_phys_3.md
        - 技術経営戦略学専攻:
          - 2022年度:
            - セッション 1: kakomonn/tokyo_university/engineering/tmi_2022_session_1.md
      - 情報理工学研究科:
        - 共通:
          - 2023年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2023_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/IST/kyotsu_2023_math_2.md
          - 2022年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2022_math_1.md
            - 数学 第2問: kakomonn/tokyo_university/IST/kyotsu_2022_math_2.md
            - 数学 第3問: kakomonn/tokyo_university/IST/kyotsu_2022_math_3.md
          - 2020年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2020_math_1.md
          - 2018年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2018_math_1.md
          - 2017年度:
            - 数学 第1問: kakomonn/tokyo_university/IST/kyotsu_2017_math_1.md
      - 新領域創成科学研究科:
        - 物質系専攻:
          - 2020年度:
            - 第3問: kakomonn/tokyo_university/frontier_sciences/materials_2020_3.md
        - 複雑理工学専攻:
          - 2020年度:
            - 第1問: kakomonn/tokyo_university/frontier_sciences/cse_2020_1.md
            - 第2問: kakomonn/tokyo_university/frontier_sciences/cse_2020_2.md
            - 第3問: kakomonn/tokyo_university/frontier_sciences/cse_2020_3.md
            - 第4問: kakomonn/tokyo_university/frontier_sciences/cse_2020_4.md
          - 2019年度:
            - 第4問: kakomonn/tokyo_university/frontier_sciences/cse_2019_4.md
            - 第8問: kakomonn/tokyo_university/frontier_sciences/cse_2019_8.md
        - 海洋技術環境学専攻:
          - 2022年度:
            - 第1~6問: kakomonn/tokyo_university/frontier_sciences/otpe_2022_all.md
          - 2020年度:
            - 第1~9問: kakomonn/tokyo_university/frontier_sciences/otpe_2020_all.md
          - 2019年度:
            - 第1~9問: kakomonn/tokyo_university/frontier_sciences/otpe_2019_all.md
      - 総合文化研究科:
        - 広域科学専攻・広域システム科学系: 
          - 2020年度:
            - 総合科目 第3問: kakomonn/tokyo_university/art_and_sciences/system_2020_3.md
      - 情報学環・学際情報学府:
        - 学際情報学専攻・生物統計情報学コース:
          - 2020年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2020_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2020_2.md
          - 2019年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2019_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2019_2.md
          - 2018年度:
            - 専門科目 第1問: kakomonn/tokyo_university/III/biostat_bioinfo_2018_1.md
            - 専門科目 第2問: kakomonn/tokyo_university/III/biostat_bioinfo_2018_2.md
      - 数理科学研究科:
        - 数理科学専攻:
          - 2022年度:
            - 専門科目 A 第1問: kakomonn/tokyo_university/mathematical_sciences/ms_2022_A_1.md
          - 2021年度:
            - 専門科目 B 第16問: kakomonn/tokyo_university/mathematical_sciences/ms_2021_B_16.md
          - 2020年度:
            - 専門科目 A 第1問: kakomonn/tokyo_university/mathematical_sciences/ms_2020_A_1.md
    - 京都大学:
      - 理学研究科:
        - 数学・数理解析専攻:
          - 2024年度:
            - 基礎科目 [1] ~ [4]: kakomonn/kyoto_university/science/math_2024_kiso_1_4.md
            - 専門科目 [13]: kakomonn/kyoto_university/science/math_2024_senmon_13.md
          - 2023年度:
            - 基礎科目 [1] ~ [3]: kakomonn/kyoto_university/science/math_2023_kiso_1_3.md
